### ISSUE TITLE
OpenXR Holographic remoting app cannot connect

### ISSUE THREAD

**Issue by Vincent-zhai-github** [microsoft/MixedRealityToolkit-Unity#10489]
## Describe the bug

Using holographic remoting through app, I cannot connect to hololens 2.

## To reproduce

1. Import the MRTK to Unity 2020 via MixedRealityFeatureTools or .unitypackages
2. Configure MRKT for OpenXR
3. Import RemotingConnect.cs (RemotingConnect.cs content is written below. RemotingConnect.cs is change from Windows XR plugin Remoting demo and [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/use-pc-resources#migrate-from-previous-holographic-remoting-apis))
4. Enable Holographic Remoting remote app of the ProjectSettings->OpenXR
5. Add to scene and configure
6. Create a empty gameobject
7. Create UI->InputField, and Rename to InputIPAddress
8. Add component RemotingConnect
9. Drag InputIPAddress gameobject to RemotingConnect of MachineName_InputField
10. Build project
11. Run app
12. Run Holographic Remoting on HoloLens 2
13. Enter the IP Address of HoloLens 2 on the PC
14. Press the C key on the keyboard to connect HoloLens 2

## Expected behavior

Press the C key will connect success. 

## Your setup (please complete the following information)

- Unity Version [2020.3.7f1]
- MRTK Version [2.7.3]

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

#### RemotingConnect.cs content

```C#

using System.Collections;
using UnityEngine;
using UnityEngine.XR.Management;
using Microsoft.MixedReality.OpenXR.Remoting;
using UnityEngine.UI;

/// <summary>
/// Sample component to configure and manage a remote connection to a HoloLens v2 device.
/// </summary>
public class RemotingConnect : MonoBehaviour
{

    /// <summary>
    /// Enabled audio to/from the connected device. This is especially important for user voice input.
    /// </summary>
    public bool enableAudio = true;

    /// <summary>
    /// Enable the streaming of video to/from device.
    /// </summary>
    public bool enableVideo = true;

    /// <summary>
    /// Maximum data rate you want to use for transmission.
    /// </summary>
    public uint maxBitRate = 9999;

    /// <summary>
    /// The name of the HoloLensV2 device to connect to.
    /// </summary>
    private string machineName;
    public InputField MachineName_InputField;

    /// <summary>
    /// The number of connection retries we will attempt.
    /// </summary>
    public int connectionRetryCount = 30;

    /// <summary>
    /// Connect to the remote device.
    /// </summary>
    public void Connect()
    {
        if (AppRemoting.TryGetConnectionState(out var connectionState, out var disconnectReason) && connectionState == ConnectionState.Connected)
            return;
        machineName = MachineName_InputField.text;
        // Connection can take a long time, especially since we need to also spin up
        // XR SDK once connected. For that reason we do most of the work in a CoRoutine.
        StartCoroutine(TryConnect());
    }

    /// <summary>
    /// Disconnect from the remove device.
    /// </summary>
    public void Disconnect()
    {
        if (AppRemoting.TryGetConnectionState(out var connectionState, out var disconnectReason) && connectionState != ConnectionState.Connected)
            return;

        // Disconnecting can also take some time given that we need to shut down the XR SDK session.
        StartCoroutine(TryDisconnect());
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.C))
        {
            Debug.Log("Attempting to connect...");

            Connect();
        }

        if (Input.GetKeyDown(KeyCode.D))
        {
            Disconnect();

            Debug.Log("Attempting to disconnect...");
        }
    }

    IEnumerator TryConnect()
    {
        // Setup the connection state information required to make a connection
        // to the remote device.
        RemotingConfiguration remotingConfiguration = new RemotingConfiguration();
        remotingConfiguration.EnableAudio = enableAudio;
        remotingConfiguration.VideoCodec = RemotingVideoCodec.Auto;
        remotingConfiguration.MaxBitrateKbps = maxBitRate;
        remotingConfiguration.RemoteHostName = machineName;
        remotingConfiguration.RemotePort = 8265;

        Debug.Log($"Connecting to {machineName}...");

        AppRemoting.Connect(remotingConfiguration);

        yield return new WaitForEndOfFrame();
        ConnectionState connectionState = ConnectionState.Connecting;
        DisconnectReason disconnectReason = DisconnectReason.None;

        int connectionTryCount = 0;

        Debug.Log(AppRemoting.TryGetConnectionState(out connectionState, out disconnectReason));
        Debug.Log("Connection state: " + connectionState);
        Debug.Log("disconnection reason: " + disconnectReason);

        // If connection fails, we'll try again, up to the number of times specified
        while (AppRemoting.TryGetConnectionState(out connectionState, out disconnectReason) && connectionTryCount < connectionRetryCount)
        {
            Debug.Log($"Still connecting to {machineName}..."
                + "\t" + "Connection state: " + connectionState
                + "\t" + "disconnection reason: " + disconnectReason);
            connectionTryCount++;
            if (connectionState == ConnectionState.Connecting)
            {
                yield return new WaitForSeconds(1);
                continue;
            }
            break;
        }

        switch (connectionState)
        {
            case ConnectionState.Connected:
                Debug.Log($"Successfully connected to {machineName} after {connectionTryCount} seconds.");

                // We've connected, so now we need to spin up XR SDK.
                yield return XRGeneralSettings.Instance.Manager.InitializeLoader();
                if (XRGeneralSettings.Instance.Manager.activeLoader != null)
                    XRGeneralSettings.Instance.Manager.activeLoader.Start();
                break;

            case ConnectionState.Disconnected:
                Debug.LogError($"Unable to connect to {machineName} after {connectionTryCount} seconds");
                ConnectionState _connectionState = ConnectionState.Disconnected;
                DisconnectReason _disconnectReason = DisconnectReason.DeviceLost;
                AppRemoting.TryGetConnectionState(out _connectionState, out _disconnectReason);
                Debug.LogError($"Connection Failure Reason {_disconnectReason}");
                break;
        }
    }

    IEnumerator TryDisconnect()
    {

        ConnectionState connectionState = ConnectionState.Disconnected;
        DisconnectReason disconnectReason = DisconnectReason.DeviceLost;
        if (AppRemoting.TryGetConnectionState(out connectionState, out disconnectReason) && connectionState == ConnectionState.Connected)
        {
            // If we have a live XR SDK session, we need to shut that before we can disconnect the remote session.
            if (XRGeneralSettings.Instance.Manager.activeLoader != null)
            {
                XRGeneralSettings.Instance.Manager.activeLoader.Stop();
                XRGeneralSettings.Instance.Manager.DeinitializeLoader();
            }

            AppRemoting.Disconnect();
            yield return new WaitForEndOfFrame();
        }

        yield return null;
    }
}


```

**Comment by davidkline-ms** [comment]
@keveleigh is investigating OpenXR issues currently

**Comment by Vincent-zhai-github** [comment]
Hi, I rasied a request 2 weeks ago, just wondering if there is any update? Please be kind enough to look into this. Thank you very much for your help.

**Comment by Vincent-zhai-github** [comment]
With the help of @meiyg0927, this problem was solved. Thanks @meiyg0927

**Comment by mertusta1996** [comment]
> With the help of @meiyg0927, this problem was solved. Thanks @meiyg0927

what was the help, how you resolved ?

**Comment by ProgrammingKiddo** [comment]
> With the help of @meiyg0927, this problem was solved. Thanks @meiyg0927

What was the solution for this issue? I'm having similar problems and the previous encountered version of the same problem ( #9465 ) doesn't seem to solve it for me.
