### ISSUE TITLE
Some BoundsControl examples are not stopping at intended 'Max' value

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10864]
## Describe the bug

Some BoundsControl examples are not stopping at intended 'Max' value, and are able to scale very large.

## To reproduce

1. Launch the Bounds Control Example scene - on the mrtk3 branch
2. See issue immediately on description window

## Expected behavior

Windows have a max intended size, and will not exceed that

## Screenshot

![BoundsScreenshot](https://user-images.githubusercontent.com/110259320/184192929-964eaed2-b14c-4642-9097-4670e6cd28a4.jpg)

## Your setup (please complete the following information)

- Unity Version 2020.3.37f1
- MRTK Version 3.0
- Commit Version 9a14d8ad28e9861d4b4077ae02168177fc9d90b1

## Target platform (please complete the following information)

- HoloLens 2

## Other Info
Possibly related to this recent issue/change

https://github.com/microsoft/MixedRealityToolkit-Unity/commit/2d9c5b77900045568d7dad7ec675cf2696277957
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10806

**Comment by Zee2** [comment]
Are you sure you're testing on that commit? This problem really should have been fixed by 2d9c5b77.

**Comment by Clandguth** [comment]
Pull did not complete this morning. Running another pass through the example scenes and will close out the issue if it doesn't repro (which is expected)

**Comment by Clandguth** [comment]
@Zee2 Have changed the bug to include the issue I am still seeing on the most recent commit. e46fee7194768f0b2babeb3ab199b59a2926901c

**Comment by Zee2** [comment]
Going to close to consolidate all of the "missing scale constraint issues" into one place.
