### ISSUE TITLE
Button class does not block events from reaching fallbackInputStack

### ISSUE THREAD

**Issue by SujeathPareddy** [Microsoft/MixedRealityToolkit-Unity#2295]
## Overview
Button class (HoloToolkit.Unity.Buttons.Button) does not mark received Event Data as used. This causes events to be handled twice, once by the button callbacks, and once by handlers inside InputManager.fallbackInputStack.

## Expected Behavior
From [/Assets/HoloToolkit/Input/README.md](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/README.md)

> handle various types of input and send them to any game object being currently gazed at, **or** any fallback object.

This means that events sent to the button shouldn't be sent to the fallback object.

## Actual Behavior
Pressing a button also activates both the fallback object's method and the callback on the button.

## Steps to reproduce

1. `git clone https://github.com/SujeathPareddy/MixedRealityToolkit-Unity.git`
2. `git checkout origin/june18_dev`
3. `git checkout 9a44898316c89` (This is an intermediate commit before I fixed the bug)
3. Open Assets/repro scene
4. Press play
5. Shift + left click on the circular button
6. Observe that two types of callbacks are emitted in the console. (relevant code is in attachtobutton.cs). The callback registered directly with the button is executed twice, possibly related to #1879.

## Fix

The bug is in Button.cs. The passed eventData parameter should call EventData.Use() before returning. 

The patched version is [here](https://raw.githubusercontent.com/SujeathPareddy/MixedRealityToolkit-Unity/june18_dev/Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs).

Demo of potentially fixed code here:
`git checkout origin/june18_dev`

Note on behaviour: If the button has no registered callbacks, then the event is not marked as used. This is a matter of opinion. I believe this makes the most sense in my app's context. Perhaps there should be a flag on the Button class.

## Unity Editor Version
2017.3 and 2017.4

## Mixed Reality Toolkit Release Version
2017.4.0.0

**Comment by keveleigh** [comment]
Ahh, good catch! This sounds like a bug to me. @cre8ivepark, was this done by-design for some reason?

**Comment by cre8ivepark** [comment]
@keveleigh I experienced the same issue on my personal projects. @paseb Could you please verify this issue? Thanks!

**Comment by SujeathPareddy** [comment]
@cre8ivepark Perhaps you can replace your Button.cs with [the patched one](https://raw.githubusercontent.com/SujeathPareddy/MixedRealityToolkit-Unity/june18_dev/Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs) and see if it gets fixed.

**Comment by SujeathPareddy** [comment]
Any update on this? I am happy to work on a pull request.

**Comment by keveleigh** [comment]
@SujeathPareddy, please feel free! This sounds like a bug that should be fixed.

**Comment by Danny2036** [comment]
Hey, I am using the Button out of the Toolkit. I pulled it for the first time a two weeks ago. I am still seeing this issue. I have a fallback event and two buttons that are both still activating the fallback. I checked the button.cs, but all the input have their own eventdata.Use(). Is there any other thing that needs to be done to get the proper functionality. When I deactivate the fallback gameobject the buttons behave as intended.

**Comment by SujeathPareddy** [comment]
Is it possible that the raycast is somehow hitting the ground before hitting the button? 

This could happen if there were some incorrect raycast flags on the button. Another possibility is that the button is somehow intersecting or overlapping with the collider of the fallback.

**Comment by Danny2036** [comment]
I have not changed any of the raycast functionality, but I am not quite sure of everything that is happening there or how to check if that's happening. If you have a suggestion I can check that though.

The button should not be overlapping with the fallback collider. The fallback is just an empty gameobject. Additionally, I placed it at 100,100,100 and I am viewing at origin, so it should not be interfering.

**Comment by SujeathPareddy** [comment]
Could you put a breakpoint on each line with eventData.use() and see if it's getting hit? I am able to see that it's getting hit on my machine.

If it isn't, then it might be some issue with the conditions in the if block. That could be mean a new bug or perhaps some issue with the way the prefab is being used.

**Comment by Danny2036** [comment]
So I was able to get the fallback function to work successfully with ButtonTraditional. When I had the breakpoint for that button it all occurs properly and I consume the event on exit, enter, clickUp, and down. But when I am using the Button it does not fire any of the method that consume the event.

**Comment by SujeathPareddy** [comment]
I can't say for sure but I think this is an issue with your prefab.

If the functions aren't being called at all, then it's probably unrelated to this issue.
