### ISSUE TITLE
[Beta] Annoying popup triggered by selecting world space canvas

### ISSUE THREAD

**Issue by phosphoer** [Microsoft/MixedRealityToolkit-Unity#3202]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit vNext

**Describe the bug**
In the vNext beta, a popup is triggered any time you select a canvas that is set to World Space with no configured camera. This also is triggered when selecting prefab assets, which will never have a configured world camera since it would need to be a scene reference. This makes it incredibly annoying to work with these prefabs. Seems like the CanvasEditorExtension should either detect this and not display the popup for assets or just not display a popup at all since the world camera may be getting configured in any number of ways at runtime outside of a serialized reference. 

Additionally, the popup tries to remove the CanvasUtility component with DestroyImmediate even on the prefab, which is not permitted and causes errors in the log. 

**To Reproduce**
1. Open a Unity project with MixedRealityToolkit vNext beta included
2. Create a UI Canvas and set to world space
3. Drag the canvas into asset window to make it a prefab

**Expected behavior**
- No popups are displayed

**Actual behavior**
- A popup is displayed upon selecting world space and every time the object is selected in the future
- A popup is also displayed upon creating a prefab of the asset, and again upon any selections of the asset, which also attempts to destroy components on the prefab causing errors in the log

**Screenshots**
![image](https://user-images.githubusercontent.com/3892683/49318096-fada5e00-f4ab-11e8-8777-f1a2b04e0574.png)

**Unity Editor Version**
2018.2.14f1

**Mixed Reality Toolkit Release Version**
MRTK vNext Beta 2018.9

**Comment by StephenHodgson** [comment]
This is by design

**Comment by StephenHodgson** [comment]
Also the errors described are fixed in #3116

**Comment by phosphoer** [comment]
@StephenHodgson Thanks for your reply, I tried your change and it does prevent the popup from appearing when selecting assets, however I think there are still problems with this approach.

1. It seems like the IsUtilityValid check in CanvasEditorExtension will only ever be true while playing in the app and directly after before next re-compile since it relies on FocusProvider property being set, which can only happen at runtime (and after since these are references to non-monobehaviour objects that will still be alive). If that is intended, I'm not sure what the value is of adding the camera reference to canvases you select at runtime. 

2. It still attempts to destroy the CanvasUtility on selected assets that already have that component added to them. Are we not expected to put this component on canvas's that will be instantiated at runtime and therefore not able to serialize a reference to the UI Raycast camera directly? I'm not clear how instantiated canvas's would work in this design. 
![image](https://user-images.githubusercontent.com/3892683/49319297-fa909180-f4b0-11e8-938f-cc36a7681a79.png)

**Comment by StephenHodgson** [comment]
Howdy, I'll double check these again to make sure you're not running into any errors.

Just a bit of background on the canvas utility.

It's needed so that we can properly raycast against the canvases with the input system, but we have the popup because someone requested that we notify users that we were modifying their component, as not setting the world camera is a valid state. Now the popup should only really show up when you initially change the canvas' mode to world space. (I'll double check to ensure this is the case).

1. `IsUtilityValid ` should be true both in edit and runtime if the Input System and Focus Provider are valid.

2. Instantiated canvases will need to manually set the world space camera to the focus provider's `UIRaycastCamera` to get the correct input events and focus state. Not much we can do there at runtime as we assume that not setting the canvas' world camera is a valid state.

**Comment by StephenHodgson** [comment]
Oh another point for 2. 

You can manually add a `CanvasUtility` after creating the canvas utility to have it auto update the world space camera to the focus provider.

**Comment by phosphoer** [comment]
As far as the popup goes, would you consider an inspector warning that recommends adding CanvasUtility to the gameobject? It could even have a button on it to add the utility. A modal popup is really disruptive since it effectively freezes the whole editor until you click ok every time you create a new canvas. With an inspector warning it would just be on the developer to add the component and you wouldn't have to play the guessing game of whether to add or remove the component in editor code. 

Regarding 2: What you describe is what I had done in the screenshot I posted, I added CanvasUtility to a canvas prefab and saw that error every time I selected the asset (with your new change).

**Comment by StephenHodgson** [comment]
> A modal popup is really disruptive since it effectively freezes the whole editor until you click ok every time you create a new canvas

It's pretty important that people take the time to stop and read it or else their canvas _will not work with the input system_. Although I suppose I could add an additional option to always add it as well.

In either case, I fixed the problem with 2.

**Comment by phosphoer** [comment]
Hm I pulled your latest changes and I am still seeing strange behavior where occasionally MixedRealityToolkit.InputSystem is null and the IsUtilityValid check fails and removes my CanvasUtility. Switching scenes / hitting play and stopping seems to temporarily fix it but it will eventually fail again.

**Comment by phosphoer** [comment]
Either of my repro projects for my new issues should suffice. [This one, for example](https://github.com/phosphoer/repro-mrtk-ui-events). Open the mrtk-unity-ui scene in Scenes/ and try selecting ui-test in the scene and also in the project.
