### ISSUE TITLE
[Beta] vNext Gaze does not work with Unity UI on device in Hololens

### ISSUE THREAD

**Issue by phosphoer** [Microsoft/MixedRealityToolkit-Unity#3218]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit vNext

**Describe the bug**
While gaze input seems to be working in the editor, I cannot get it working on device (Hololens). I have a CanvasUtility on my UI canvas, and when I build for Hololens and run on device I do not get any highlight effect when gazing at a button, nor am I able to press it with air tap. 

**To Reproduce**
[Repro project](https://github.com/phosphoer/repro-mrtk-ui-device)
1. Download the repro project and open in Unity
2. Run the Scenes/mrtk-unity-ui scene in editor
3. Drag the camera to the left in the scene view and verify that the button is highlighted by the gaze cursor
4. Build for UWP and deploy to a Hololens
5. Run the app on device and observe that the button is not highlighted by gaze 

**Expected behavior**
The UI button is highlighted by gaze on device

**Actual behavior**
The UI button is not affected by gaze on device

**Unity Editor Version**
2018.2.14f1

**Mixed Reality Toolkit Release Version**
vNext Beta

**Comment by StephenHodgson** [comment]
Can you also verify that the canvas utility was on the UI you were trying to focus on?

**Comment by StephenHodgson** [comment]
Oh this isn't really a bug as it's not using the beta focus provider.

Seems this project is using the refactored one in the PR that hasn't been merged yet.

I'll move over the test scenes into the PR and make sure these are addressed.

**Comment by phosphoer** [comment]
> Can you also verify that the canvas utility was on the UI you were trying to focus on?

I mentioned this was the case in the bug description. 

> Oh this isn't really a bug as it's not using the beta focus provider.
> Seems this project is using the refactored one in the PR that hasn't been merged yet.

Yes I was using the one from the pull request you mentioned contained fixes, in hopes this was one of them. The bug is also present in the latest beta release. 

Is there perhaps something easy I could be missing? Is there some platform-specific settings in one of the configuration profiles that might be excluding something I need in the build?

**Comment by StephenHodgson** [comment]
> Is there perhaps something easy I could be missing? Is there some platform-specific settings in one of the configuration profiles that might be excluding something I need in the build?

I don't think so, but I'm def interested in getting it fixed asap

**Comment by StephenHodgson** [comment]
@phosphoer this seemed to have gotten fixed with your PR as well. Tested it again with your changes and it works as intended. Let me know what your results are as well and we can close this issue too.

**Comment by phosphoer** [comment]
@StephenHodgson Interesting, I had the same thought and tried it but didn't seem to fix anything for me. On device I get no raycasting on the canvas at all, the EventSystem.RaycastAll method returns 0 results despite a canvas utility being present.

**Comment by phosphoer** [comment]
Figured it out. The UI Raycast Camera is being assigned target display index 1, which is invalid. Setting it to 0 fixes the issue. There are a bunch of other unnecessary configurations being done to it, including setting it ortho which doesn't seem to hurt but I don't think is correct. Will make another PR soon.
