### ISSUE TITLE
InteractableHighlight

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#3572]
## Overview
InteractableHighlight not working at all

## Expected Behavior
When a gaze cursor strikes an object, the InteractableHighlight should activate the Highlight Material

## Actual Behavior
Nothing happens

## Steps to reproduce
Create a project as described here 
https://www.youtube.com/watch?v=-ODnfcv5Rzg&list=PLCK8aOPy3e4JhG06GRdlJkmNXoITEewxV

## Unity Editor Version
2018.3.6f1

## Mixed Reality Toolkit Release Version
2.0.0 beta 2.

## Diagnosis
The issue is line 267 in OnFocusEnter. That says  **if (HasFocus)** and that should be  **if (!HasFocus)**
and then it works

**Comment by LocalJoost** [comment]
Do you want a PR for one bang? ;)

**Comment by keveleigh** [comment]
I'm unable to repro this. The line described in Diagnosis above is correct, because `HasFocus` will already be true at that point.

Likely, this observation was a side effect of BaseFocusHandler's incorrect interfaces, which was fixed by #3702. Please re-open if you're still able to repro after that fix.

**Comment by LocalJoost** [comment]
@keveleigh this still happens on my side, even after refreshing the MRKT from the MRTK_development branch. I still needed to change if(HasFocus) to if(!HasFocus) . Which is also logical from a standpoint of pure looking at the code itself:
public override void OnFocusEnter(FocusEventData eventData)
{
    base.OnFocusEnter(eventData);

    **if (HasFocus)**
    {
        Highlight = true;
    }
}

/// <inheritdoc />
public override void OnFocusExit(FocusEventData eventData)
{
    base.OnFocusExit(eventData);

    Highlight = false;
}

This simply does not make sense. If it has focus, it is already highlighted, to highlighting does not make sense.

**Comment by LocalJoost** [comment]
You are right. This has been fixed in dev. But now I found another issue. Coming soon to you ;)
