### ISSUE TITLE
Trigger planes in pressable button won't scale with button

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4216]
## Describe the bug

Planes for defining the distances for a button to trigger / release are not scaled with the button.

## To reproduce

Create a pressable button and up or downscale the button. Observe the debug planes showing the maxDistance / releaseDistance etc won't adjust accordingly

## Expected behavior

Planes should either adjust accordingly to the scaling or have a setting to allow them to be scaled with the button (make distances local checkbox?)

## Your Setup (please complete the following information)

- MRTK Version v2 RC1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
I believe that this was fixed by #4144 based on the following comment in that PR:

_Yes there's at least 2 tickets that are fixed with this PR (#4219, #4216) - but I just wanted to open this as a draft for having a discussion about it. If possible I'd like to avoid having the migration step (if we have to keep it in it should be moved out of the class)._

**Comment by thalbern** [comment]
not fixed! i was asked to close the draft PR - there's a comment in there that says there's going to be a second PR with the actual fix - the draft was just for discussing the fixes
