### ISSUE TITLE
Sharing Service: Unity Editor crashes when setting client role to Unspecified or Secondary

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#506]
Repro Steps:

1. Open `SharingTest.scene`
2. Set `Sharing.prefab` Client Role to Unspecified or Secondary
3. Start Sharing Service
4. Play in editor
5. Observe crash report.

**Comment by paulmriordan** [comment]
Do you have any idea when this bug should be fixed?

**Comment by StephenHodgson** [comment]
When the stabilization branch is merged into master for the [2017.2.1.1 Patch](#1698) is released.

**Comment by PulseJK** [comment]
Hello,
Actually I think that the bug is stille not fixed. I got a Runtime error when i try to launch the sharingTest scene with a secondary or unspecified client role with the sharingService Running

![unitycrash](https://user-images.githubusercontent.com/33837716/37155041-23132d3a-22e2-11e8-9716-029da91ce279.PNG)

**Comment by StephenHodgson** [comment]
@davidkline-ms, @keveleigh can we verify this is fixed?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
