### ISSUE TITLE
Fails to build when running via Build Window / Appx Build Options when no VS solution already created

### ISSUE THREAD

**Issue by Naphier** [microsoft/MixedRealityToolkit-Unity#5434]
## Describe the bug
Trying to use these new build tools and figure out how to get this rolling on CI/CD. 
In Build Window
- If we run Unity Build Options to generate the VS project then run Appx Build Options everything works as expected.
- If we run from Appx build options without a generated VS project the build fails. I believe this is the failure reason:
```
C:\VRR_Repos\WARC-LSOD\Builds\WSAPlayer\WARC-LSOD.sln.metaproj : error MSB4126: The specified solution configuration "master|" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\VRR_Repos\WARC-LSOD\Builds\WSAPlayer\WARC-LSOD.sln]
UnityEngine.Debug:Log(Object)
VRR.MixedRealityToolkit.<>c__DisplayClass1_0:<StartProcessAsync>g__OnOutputDataReceived|2(Object, DataReceivedEventArgs) (at Assets/Editor/From MRTK/Extensions/ProcessExtensions.cs:106)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
```
- This same message occurs whether the _Appx Build Options_ are set to Release or Master. Currently set to IL2CPP, Release, x86

## To reproduce
See description. 

## Expected behavior
That the VS project would build and then the appxbundle would build without errors.

## Your Setup (please complete the following information)
- Unity Editor 2018.3.1f1
- MRTK SDK RC 2.0.0
- Windows SDK 10.0.18922.0

## Target Platform (please complete the following information)
- HoloLens

## Additional info
We also get a few compiler errors, but these happen no matter if we're just building the VS project or doing both VS proj and appx bundle. They do not seem to affect the build. Also they don't appear when building via Unity's Build Settings window. Thought they'd go away with Windows SDK 10.0.18922.0 but nope, probably a Unity issue.
```
Reference rewriter: Error: field `System.Numerics.Vector3 Windows.Perception.People.HandMeshVertex::Normal` doesn't exist in target framework. It is referenced from Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.dll at System.Void Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityArticulatedHand::UpdateControllerData(UnityEngine.XR.WSA.Input.InteractionSourceState).
UnityEngine.Debug:LogError(Object)
PostProcessWinRT:RunReferenceRewriter() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:1064)
PostProcessWinRT:Process() (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWinRT.cs:217)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
VRR.MixedRealityToolkit.UnityPlayerBuildTools:BuildUnityPlayer(IBuildInfo) (at Assets/Editor/From MRTK/BuildAndDeploy/UnityPlayerBuildTools.cs:115)
VRR.MixedRealityToolkit.<BuildPlayer>d__2:MoveNext() (at Assets/Editor/From MRTK/BuildAndDeploy/UwpPlayerBuildTools.cs:108)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<BuildPlayer>d__2&)
VRR.MixedRealityToolkit.UwpPlayerBuildTools:BuildPlayer(UwpBuildInfo, CancellationToken)
VRR.MixedRealityToolkit.<BuildPlayer>d__1:MoveNext() (at Assets/Editor/From MRTK/BuildAndDeploy/UwpPlayerBuildTools.cs:89)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<BuildPlayer>d__1&)
VRR.MixedRealityToolkit.UwpPlayerBuildTools:BuildPlayer(String, Boolean, CancellationToken)
VRR.MixedRealityToolkit.<BuildAll>d__71:MoveNext() (at Assets/Editor/From MRTK/BuildAndDeploy/BuildDeployWindow.cs:1091)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start(<BuildAll>d__71&)
VRR.MixedRealityToolkit.BuildDeployWindow:BuildAll(Boolean)
VRR.MixedRealityToolkit.<>c:<AppxBuildGUI>b__64_2() (at Assets/Editor/From MRTK/BuildAndDeploy/BuildDeployWindow.cs:628)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()
```

**Comment by lpraedel** [comment]
I had the same error. I fixed it by changing `buildinfo `in class `UwpPlayerBuildTools `in method `BuildPlayer `on line 59 to:
` var buildInfo = new UwpBuildInfo
            {
                Configuration = UwpBuildDeployPreferences.BuildConfig,
                BuildPlatform = EditorUserBuildSettings.wsaArchitecture,
                OutputDirectory = buildDirectory,
                Scenes = EditorBuildSettings.scenes.Where(scene => scene.enabled).Select(scene => scene.path),
                BuildAppx = !showDialog,
                // Configure a post build action that will compile the generated solution
                PostBuildAction = PostBuildAction
            };`
originally it was:
`            var buildInfo = new UwpBuildInfo
            {
                OutputDirectory = buildDirectory,
                Scenes = EditorBuildSettings.scenes.Where(scene => scene.enabled).Select(scene => scene.path),
                BuildAppx = !showDialog,
 // Configure a post build action that will compile the generated solution
                PostBuildAction = PostBuildAction
            };`
I also had to change the path to "MSBuild.exe" in class `UwpAppxBuildTools`, method  `FindMsBuildPathAsync` in line 189 from `return $@"{bestPath}\MSBuild\15.0\Bin\MSBuild.exe";`
to `return $@"{bestPath}\MSBuild\Current\Bin\MSBuild.exe";`

**Comment by Naphier** [comment]
Thanks
Turns out for some reason it wasn't reading in `EditorUserBuildSettings.wsaArchitecture` the CL was
```
msBuildPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
args:
"C:\VRR_Repos\WARC-LSOD\Builds\WSAPlayer\WARC-LSOD.sln" /t:Build /p:Configuration=master;AppxBundle=Always /p:Platform= /verbosity:m```
Notice the missing param for Platform.
Since this and the Configuration parameter are critical I think it would be a good idea to do some error checks around it.
I'll work up a PR.

**Comment by wiwei** [comment]
A couple of questions here: 

We fixed a build related issue (the master| thing) in mrtk_development and I'm not 100% that it made the cut for the RC2 release - it might be helpful if you guys could check to see if you're still seeing this issue on latest mrtk_development

Also regarding the reference rewriter issues, those were associated with a Unity bug will be fixed in one of the newer 2018.4.x drops (I don't remember exactly which, but something > 2018.4.3)

**Comment by wiwei** [comment]
Also note that we had some issues with 2019 which got fixed here:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5415

So yeah, definitely take latest mrtk_development for a spin and let us know!

**Comment by Naphier** [comment]
Will try to pull from dev and see if issue persists. Thought I saw something about the reference rewriter. Doesn't seem to actually cause issues.

**Comment by Naphier** [comment]
Hey @wiwei the question on the PR was:
The PR is meant as a failsafe, so whether it works correctly now or not is't completely the question. I don't think the issue was MRTK, but Unity failing to load / allow EditorUserBuildSettings to be read. So the PR implements a failsafe in case this happens to others. Build platform and configuration are critical values to pass to MSBuild, so we must check that those are valid. The PR does that and if they aren't it sets them to a safe default and provides a warning to the dev/user. Just like we do with paths - validate.

The question for the PR is: Should we just fail the build with clear errors or should we fall back onto safe defaults as I am doing in the PR #5442 . 

I can pull mrtk_development, but this is an intermittent issue and difficult to reproduce. While I was writing the failsafes the darn thing started actually getting the values from EditorUserBuildSettings. This failsafe would prevent annoying failures like this and provide the dev/user with clear messaging as to what happened.

**Comment by wiwei** [comment]
The reason I ask is, from what I remember, the first build was always not working, but this had gotten fixed in mrtk_development. I think we can still go with the change just in case, though it might also have some non-predictable defaults (i.e. if someone wants x64 / release but now we default them to x86 / master, that would be a weird behavior). i.e. the fix here should be to do this check earlier in the build process (which I *think* we have actually addressed in latest, which is why I'm asking for you to double check with mrtk_development)

i.e. the issue was intermittent in that folks would hit it the first time they tried to use things, but then gets resolved after the settings get updated during a single build process.

If you're still hitting this with latest I think i'll be good to proceed with the PR, it's just that error message is something that I remember we literally fixed a while back (but after the RC2 release) so I don't think we should try to apply a bandaid unless it's still needed.

As for reference rewriter, please see my earlier comment in  this thread - it's a Unity bug that happens if you try to use the new Windows SDK APIs in v18362
