### ISSUE TITLE
VR throwing using Manipulation Handler is not functional

### ISSUE THREAD

**Issue by swhook52** [microsoft/MixedRealityToolkit-Unity#7178]
## Describe the bug

Using MRTK 2.2.0 in VR with WMR Acer headset and controllers, I am unable to throw an object defined with a Rigidbody and Manipulation Hander and Near Interaction Grabbable with release behavior set to "Everything". The object simply drops to the ground without calculating release velocity and throwing the object.

MRTK Slack indicated this is a feature request, but based on the "Release" behavior indicating what should happen when you let go of the object, I see this as functionality that is lost in VR.

## To reproduce

1. Configure a scene with MRTK
2. Add in the hack to get VR controllers to grab items by changing the MRTK profile to explicitly set "GrabPointer" to include the controller type "Windows Mixed Reality" and "Generic Open VR".
3. Create a cube with a rigidbody, Manipulation Handler and Near Interaction Grabbable.
4. Ensure the Manipulation Handler has the "Release" behavior set to "Everything"
5. In VR, pick up the cube and attempt to throw it.
6. See that it drops to the ground instead.

## Expected behavior

When releasing the cube the "Release" behavior should calculate the velocity of the cube to have it throw in an arc.

## Your setup (please complete the following information)

- Unity Version 2018.4
- MRTK Version v2.2.0

## Target platform (please complete the following information)

- WMR immersive
- OpenVR

## Additional context

Even the sample hand interaction demos don't allow me to throw objects. They just fall after releasing them.

**Comment by wiwei** [comment]
@thalbern @MenelvagorMilsom I thought there was some stuff around maintaining velocity upon release (though maybe this was in the new versions?)

**Comment by swhook52** [comment]
> @thalbern @MenelvagorMilsom I thought there was some stuff around maintaining velocity upon release (though maybe this was in the new versions?)

I believe that's the Release Behavior I'm referencing above.

![ManipulationHandler](https://user-images.githubusercontent.com/2775085/73382318-4695bc80-4295-11ea-996c-cfec2212ba79.jpg)

**Comment by wiwei** [comment]
Oh I meant, I remember there were issues with this in the old version (i.e. Manip Handler) but I wasn't sure if some of these were fixed in the newer versions (Object Manipulator)

**Comment by lorak41** [comment]
I have exact same problem. Are there any simple workarounds to fix it?

**Comment by Adam7288** [comment]
Mirroring the above comments

**Comment by chetu3319** [comment]
The current calculation provides velocity to the grabbed object, but one that provided velocity is of controller's velocity which is not same as of the distant grabbed object. 

You can check the [code submitted in the previous commit](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5259/commits/2a73e34b2cb83fb7d2d59260f48cccefc1dfc8f8)

My workaround is to update this code to the ray's hit point instead of the controller's position. 
OR Calculate the Velocity using a separate script on the Grabbed game object.

**Comment by keveleigh** [comment]
@RogPodge Is this fixed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9733?

**Comment by RogPodge** [comment]
Should be!

**Comment by yifeifang** [comment]
I've recently come across this issue. Far field input works just as expected however the `nearinteractionGrabbable` still won't let me throw the object

**Comment by RogPodge** [comment]
Are you using the `ObjectManipulator`? The `ManipulationHandler` class has been deprecated in favor of `ObjectManipulator`

**Comment by yifeifang** [comment]
I'm using the new object manipulator
> Are you using the `ObjectManipulator`? The `ManipulationHandler` class has been deprecated in favor of `ObjectManipulator`

**Comment by RogPodge** [comment]
Can you include video and repro steps? #9733 should have addressed this scenario, but if there's a configuration we missed more data would be very helpful to tackle it.

**Comment by RogPodge** [comment]
Looking into that PR more, it seems like you may be feeling the dampened velocity effect which occurs when using near manipulation and the object manipulator. We made a decision in that PR to not maintain an objects original velocity when releasing it with near interaction, since you can end up throwing objects somewhat uncontrollably fast. We'll discuss internally whether to change this decision.

**Comment by yifeifang** [comment]
> Can you include video and repro steps? #9733 should have addressed this scenario, but if there's a configuration we missed more data would be very helpful to tackle it.

https://youtu.be/LtERfsiGjAc Here is a video demo showed that nearfield didn't work while far field worked just fine. I'm using the lastest MRTK object manipulator script with a rigid body. Release is set to everything
![image](https://user-images.githubusercontent.com/29108355/163100474-b03fc202-e96d-4c7a-a835-47a6df90f65c.png)
![image](https://user-images.githubusercontent.com/29108355/163100495-8a45860d-338c-4a86-8578-d5fbbc848625.png)

**Comment by yifeifang** [comment]
```
        private void ReleaseRigidBody(Vector3 velocity, Vector3 angularVelocity)
        {
            if (rigidBody != null)
            {
                rigidBody.useGravity = wasGravity;
                rigidBody.isKinematic = wasKinematic;

                // Match the object's velocity to the controller for near interactions
                // Otherwise keep the objects current velocity so that it's not dampened unnaturally
                //if (isNearManipulation)
                //{
                //    if (releaseBehavior.IsMaskSet(ReleaseBehaviorType.KeepVelocity))
                //    {
                //        rigidBody.velocity = velocity;
                //    }

                //    if (releaseBehavior.IsMaskSet(ReleaseBehaviorType.KeepAngularVelocity))
                //    {
                //        rigidBody.angularVelocity = angularVelocity;
                //    }
                //}
            }
        }
```
The video result is after comment out this section of code. Which I think is the velocity damping you have mentioned?

**Comment by yifeifang** [comment]
@RogPodge It seems like the MR should fix this issue. However I just updated to the latest MRTK and tried with same setting I still couldn't throw an object with near interactable. Is this desired behavior? Or it's separate issue

**Comment by BarboraAtVResearch** [comment]
Hi, I've had the same problem. Disabling the "Smoothing near" option solved it in my case. Did you try something like that?

**Comment by yifeifang** [comment]
Let me give it a try! thanks for the input

**Comment by yifeifang** [comment]
> Hi, I've had the same problem. Disabling the "Smoothing near" option solved it in my case. Did you try something like that?

![image](https://user-images.githubusercontent.com/29108355/173220490-322a30f8-0b1f-460a-8448-f0147fe85244.png)
I've tried with disable smoothing. And here is a screen shot for my setting. It's still not throwable. Am i doing something wrong here?

**Comment by BarboraAtVResearch** [comment]
My settings are quite different, because I was going for behavior more similar to SteamVR, so no far or two-handed manipulation. I'm including the screenshot.
![image](https://user-images.githubusercontent.com/68519689/173614366-9a903968-3260-41f0-a9bd-12b116232999.png)
If you want your controller (not just hands) to be able to near-manipulate, you actually have to add the new pointer option for the controller of choice (I did that for Oculus):
![image](https://user-images.githubusercontent.com/68519689/173614957-d65010dc-f273-4a60-930b-b43ad2cb7c2d.png)
The prefab is actually just a duplicate of standard Poke pointer with minor setting changes:
![image](https://user-images.githubusercontent.com/68519689/173615291-81dd86c7-43f2-429f-b977-7043fa0980f4.png)
Unity version 2020.3.33 MRTK 2.7.3.0

**Comment by yifeifang** [comment]
thanks for the detailed reply! Could you show me your rigid body setting as well? I'm wondering it might by the mass and acceleration setting are mess me up! Again really appreciate your help!> My settings are quite different, because I was going for behavior more similar to SteamVR, so no far or two-handed manipulation. I'm including the screenshot.
> 
> ![image](https://user-images.githubusercontent.com/68519689/173614366-9a903968-3260-41f0-a9bd-12b116232999.png)
> 
> If you want your controller (not just hands) to be able to near-manipulate, you actually have to add the new pointer option for the controller of choice (I did that for Oculus):
> 
> ![image](https://user-images.githubusercontent.com/68519689/173614957-d65010dc-f273-4a60-930b-b43ad2cb7c2d.png)
> 
> The prefab is actually just a duplicate of standard Poke pointer with minor setting changes:
> 
> ![image](https://user-images.githubusercontent.com/68519689/173615291-81dd86c7-43f2-429f-b977-7043fa0980f4.png)
> 
> Unity version 2020.3.33 MRTK 2.7.3.0
