### ISSUE TITLE
Can't build appx from solution.

### ISSUE THREAD

**Issue by Hitomilras** [Microsoft/MixedRealityToolkit-Unity#840]
I trying to build APPX from solution, but i getting error code -1 while building appx... 

This console appears, show me this error and close automatically. 
![image](https://user-images.githubusercontent.com/30040189/29042590-35e44490-7bc0-11e7-9f95-01a7dc800adc.png)

Tryed to build with VS 2015 on clean windows (virtual machine), on VS 2017, on VS 2017 with 2015 installed too, nothing good happens... Error code -1.

**Comment by StephenHodgson** [comment]
Can't read the Russian, but it looks like you're building XAML, correct?

**Comment by Hitomilras** [comment]
Hi, sorry for Russian. Can’t answer you question. I click “Build appx frpom solution” button in Unity editor (using holotoolkit) and getting this error.

Отправлено из Почты для Windows 10

От: Stephen Hodgson
Отправлено: 7 августа 2017 г. в 22:38
Кому: Microsoft/HoloToolkit-Unity
Копия: Hitomilras; Author
Тема: Re: [Microsoft/HoloToolkit-Unity] Can't build appx from solution.(#840)

Can't read the Russian, but it looks like you're building XAML, correct?

**Comment by Hitomilras** [comment]
ohh, i understand. No, i don't trying to build XAML. In project settings i
see D3D. But maybe by default Holotoolkit build window use XAML.

**Comment by StephenHodgson** [comment]
No it's up to the build options. Both XAML and D3D should work.

Please double check and make sure you have all the windows 10 sdks installed.

**Comment by Hitomilras** [comment]
I will check this right now. 10 minutes.
I noticed, that VS path is empty due to the log.error





Отправлено из Почты для Windows 10

От: Stephen Hodgson
Отправлено: 7 августа 2017 г. в 22:56
Кому: Microsoft/HoloToolkit-Unity
Копия: Hitomilras; Author
Тема: Re: [Microsoft/HoloToolkit-Unity] Can't build appx from solution.(#840)

No it's up to the build options. Both XAML and D3D should work.
Please double check and make sure you have all the windows 10 sdks installed.

**Comment by Hitomilras** [comment]
Checked. I install all... And download latest version of holotoolkit (for 2017.1.f03 unity).
Now getting this errors:
Unable to find a valid path to Visual Studio Instance!

MSBuild.exe is missing or invalid (path=). Note that the default version is 14.0

**Comment by StephenHodgson** [comment]
Could be that our paths are hard coded in English, and your path may include cyrillic.

**Comment by StephenHodgson** [comment]
Be sure to follow getting started guidelines.

https://github.com/Microsoft/HoloToolkit-Unity/blob/master/GettingStarted.md

**Comment by Hitomilras** [comment]
I'm shure about getting started guidelines. Cyrillic symbols is possible, will check it.

**Comment by Hitomilras** [comment]
Maybe i can manually select MSBuild patch?

**Comment by Hitomilras** [comment]
Build appx from solution in VS. Tomorrow check if it works fine on the hololens.

**Comment by jessemcculloch** [comment]
@Hitomilras - Did you have any update on this?

**Comment by Hitomilras** [comment]
All works fine if just build solution in VS...) 
But build appx button in Unity doesn't work)

**Comment by nick7ikin** [comment]
Faced the same error message
(MSBuild.exe is missing or invalid (path=). Note that the default version is 14.0)

Try to install to Visual Studio MSBuilder and Windows 10 SDK* packages

**Comment by XPav** [comment]
I got this error if I had SDK 10.0.14393.0 selected.  Changing SDK to 10.0.15063.0 changed the MSBuild version to 15, and then it built.

I do not have Visual Studio 2015 installed, but I do have the 14393 SDK installed via Visual Studio 2017.

**Comment by StephenHodgson** [comment]
@XPav This was fixed in #981 but it's not in the latest release.

**Comment by thewizarder** [comment]
I still get this using the MRTK when I try to build an appx package fro inside Unity
